[[main]]
  name = "Home"
  url = ""
  weight = -110

#[[main]]
#  name = "Archives"
#  url = "post/rich-content/"
#  weight = -106

# Submenus are done this way: parent -> identifier
# [[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
# [[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
# [[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

[[main]]
  name = "Privacy Policy"
  url = "privacy/"
  weight = -106

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/kcraigo"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/KeithCraigo"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/keithcraigo"
  [[social]]
  name = "youtube"
  weight = 3
  url = "https://www.youtube.com/webdevbythebay"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/webdevbythebay"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://www.instagram.com/rodneykc/"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"